# Generated by Django 4.2.6 on 2023-10-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handelExcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
