# Generated by Django 4.2.6 on 2023-10-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handelExcel', '0006_alter_usedcar_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcar',
            name='price',
            field=models.IntegerField(),
        ),
    ]
